"""add indexes to user_metrics

Revision ID: 030cadc92f71
Revises: 53d6aac5ab79
Create Date: 2026-02-22 04:31:44.806472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030cadc92f71'
down_revision: Union[str, Sequence[str], None] = '53d6aac5ab79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_metrics_location', 'user_metrics', ['location'], unique=False)
    op.create_index('idx_user_metrics_ltv', 'user_metrics', ['lifetime_value'], unique=False)
    op.create_index('idx_user_metrics_orders_23d', 'user_metrics', ['orders_last_23_days'], unique=False)
    op.create_index('idx_user_metrics_orders_30d', 'user_metrics', ['orders_last_30_days'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_metrics_orders_30d', table_name='user_metrics')
    op.drop_index('idx_user_metrics_orders_23d', table_name='user_metrics')
    op.drop_index('idx_user_metrics_ltv', table_name='user_metrics')
    op.drop_index('idx_user_metrics_location', table_name='user_metrics')
    # ### end Alembic commands ###
