"""create user_metrics table

Revision ID: 457329b15481
Revises: 1ee2c12df112
Create Date: 2026-02-22 04:10:21.345060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457329b15481'
down_revision: Union[str, Sequence[str], None] = '1ee2c12df112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('orders_last_7_days', sa.Integer(), nullable=True),
    sa.Column('orders_last_23_days', sa.Integer(), nullable=True),
    sa.Column('orders_last_30_days', sa.Integer(), nullable=True),
    sa.Column('lifetime_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_metrics')
    # ### end Alembic commands ###
